repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-added-large-files
- repo: https://github.com/jumanjihouse/pre-commit-hooks.git
  rev: 2.1.5
  hooks:
  - id: shellcheck
    args: ['--shell=bash', '--color=always', '--external-sources']
    additional_dependencies: []
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v7.20.0
  hooks:
  - id: eslint
- repo: local
  hooks:
    - id: tests
      name: Mocha tests
      language: system
      entry: npm test
      always_run: true
      pass_filenames: false
      require_serial: true
- repo: local
  hooks:
    - id: coverage
      name: Ensure that coverage hasn't decreased per-file
      language: system
      entry: ./check-coverage last-coverage-summary.json
      always_run: true
      pass_filenames: false
      require_serial: true
- repo: local
  hooks:
    - id: webpack
      name: Webpack dry run
      language: system
      entry: sh -c 'TMPDIR="$(mktemp -d)"; npx webpack --output-path "${TMPDIR}"; EXITCODE=$?; rm -r "${TMPDIR}"; exit "${EXITCODE}"'
      always_run: true
      pass_filenames: false
      require_serial: true
